<?php


namespace api\lib\exception;

//use think\Exception;
use think\exception\Handle;
use think\Response;
use Throwable;

class ExceptionHandler extends Handle
{
    public function render($request, Throwable $e): Response
    {
        return show(config('error'),$e->getMessage()); // TODO: Change the autogenerated stub
    }
}